### ISSUE TITLE
levels of correlation analysis

### ISSUE THREAD

**Issue by Jeiyoon** [e0397123/D-score#1]
Hi 😄

thank you for your great works in advance. It's really helpful.

I'd like to ask you a question.

Could you let me know the differences among "System-level", "Conversation-level", and "Turn-level"  analysis?

I read your paper and i don't get it 

Thank you so much

Best regards

Jeiyoon

**Comment by e0397123** [comment]
Hi Jeiyoon,

**The system-level correlation** means that for a group of dialogue systems to rank, each system will receive a single metric score. Then we do correlation between the list of scores and the corresponding human annotated scores. In the experiment, one can simply average the scores of all the responses from a dialogue system in the test set and treat the averaged score as the system score. (same procedure for the corresponding human scores)

**Conversation-level correlation** intends to rank a list of conversations. In the interactive human evaluation setting, the annotator will give a single rating to the entire conversation. Then the automatic metric will also need to assign a single score to the entire conversation. Correlation is performed between these two groups  of scores. One simple way to obtain a single conversational level metric score is to average the scores assigned to all the context-response pairs within the conversation.

**Turn-level**  is the most fine-grained category. It is the common approach in static evaluation whereby we have multiple context-response pairs, the annotators will annotate the quality of the response. Then, the metric will assign score for each context-response pair. Correlation is performed between these two groups of scores.

Hope this clarifies your question!

**Comment by Jeiyoon** [comment]
Wow your explanation is crystal clear!

I get it and I really appreciate it

Have a great day!

**Comment by e0397123** [comment]
> Wow your explanation is crystal clear!
> 
> I get it and I really appreciate it
> 
> Have a great day!

No problem, you too have a great day!
